### ISSUE TITLE
I'm looking for training

### ISSUE THREAD

**Issue by sandroventuroni** [skuvault/magentoAccess#28]
Hi Guys

I'm a c# developer but most of my experience is Winforms, and I have to develop an integration between our ERP and Magento

I'm looking for someone that can provide some training and/or develop some basic class that read and write data in Magento, then I'll provide to cut and copy in my solution

Feel free to email me sandro.venturoni@gmail.com for any question or proposal

Regards

**Comment by slav** [comment]
Hi Sandro. We don't provide any training or custom development. If you want to develop some additional functionality and provide a PR we'll evaluate it and try to merge it in.
